### ISSUE TITLE
Show errors in the preview window

### ISSUE THREAD

**Issue by pfgithub** [pfgithub/scpl-editor#4]
Also with a jump button to jump to the part of the code with the error

**Comment by internetgho5t** [comment]
Probably just make the preview generated on a button press rather than automatically whenever you change the code

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by electrikmilk** [comment]
I can make some front-end dom and css for error messages with-in the preview. I’ve noticed in using the editor, having the error displayed visually rather than in something you see when you hover over the error in the editor would be much more helpful.
